name: Check release tag
on:
  schedule:
    - cron:  '* * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release tag
        run: |
          curl -sL https://api.github.com/repos/oobabooga/text-generation-webui/releases/latest | \
          jq -r ".tag_name" > oobabooga-tgw-latest.txt
      - name: Check for modified files
        run: echo "modified=$([ -z "`git status --porcelain`" ] && echo false || echo true)" >> $GITHUB_ENV
      - name: Commit latest release tag
        if: ${{ env.GITHUB_OUTPUT }} == "true"
        run: |
          git config --global user.name 'Wolfsauge'
          git config --global user.email 'no@email'
          git commit -am "New release version"
          git push
