name: Check for new oobabooga-tgw release tag
on:
  schedule:
    - cron:  '0,10,20,30,40,50 * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/oobabooga/text-generation-webui/releases/latest | \
          jq -r ".tag_name" > oobabooga-tgw-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Wolfsauge'
          git config --global user.email 'no@email'
          git commit -am "New release version"
          git push
