name: Check for new commits
on:
  workflow_dispatch:
  schedule:
    - cron:  "22,52 * * * *"

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch latest commit checksum from GitHub API
        run: |
          curl -sL https://api.github.com/repos/oobabooga/text-generation-webui/commits | \
          jq ".[0] | .sha" > oobabooga-tgw-latest.txt
      - name: Check for null response
        run: |
          if grep -qE '^null$' oobabooga-tgw-latest.txt; then
            exit 1
          fi
      - name: Check for modified files
        run: echo "modified=$([[ -z `git status --porcelain` ]] && echo false || echo true)" >> $GITHUB_ENV
      - name: Commit possible changes
        if: ${{ env.modified }} == "true"
        run: |
          git config --global user.name 'jacoby1218'
          git config --global user.email 'no@email'
          git commit -am "New commit discovered"
          git push
